filebeat.inputs:
  - type: log
    id: linux-auth-logs
    enabled: true
    paths:
      - /var/log/auth.log
    fields:
      environment: poc
      source_type: linux_auth
      project: banking-siem
      source_host: <LINUX_SOURCE_HOST>
    fields_under_root: false

  - type: log
    id: linux-system-logs
    enabled: true
    paths:
      - /var/log/syslog
    fields:
      environment: poc
      source_type: linux_system
      project: banking-siem
      source_host: <LINUX_SOURCE_HOST>
    fields_under_root: false

processors:
  - add_host_metadata: {}

output.elasticsearch:
  hosts: ["http://<OPENSEARCH_HOST_IP>:9200"]
  index: "logs-linux-%{+yyyy.MM.dd}"

setup.template.enabled: false
setup.ilm.enabled: false
